#Este es un archivo Makefile que hace mas facil el acceso a comandos definidos por el usuario. Buscar si se tiene dudas Makefile
prog1:
	gcc src/inciso1/practica3.c -o bin/bin1/practica3
prog2:
	gcc src/inciso2/pro2.c -o bin/bin2/pro2
prog3:
	gcc src/inciso3/prog3.c -o bin/bin3/prog3
co1:
	bin/bin1/practica3
co2:
	bin/bin2/pro2
co3:
	bin/bin3/prog3
bp1:
	rm -f bin/bin1/practica3
bp2:
	rm -f bin/bin2/pro2
bp3:
	rm -f bin/bin3/prog3
